# Generated by Django 4.1.2 on 2022-10-31 14:02

from django.db import migrations, models
import eshop_contact.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=eshop_contact.models.upload_image_path, verbose_name='تصویر')),
                ('full_name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=100, verbose_name='ایمیل')),
                ('subject', models.CharField(max_length=200, verbose_name='عنوان پیام')),
                ('text', models.TextField(verbose_name='متن پیام')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(verbose_name='خوانده شده / نشده')),
            ],
            options={
                'verbose_name': 'تماس با ما',
                'verbose_name_plural': 'تماس های کاربران',
                'ordering': ['created_on'],
            },
        ),
    ]
