# Generated by Django 4.1.2 on 2022-10-25 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='slug',
        ),
    ]
