# Generated by Django 4.1.2 on 2022-10-31 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_menu', '0002_remove_menu_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'منو', 'verbose_name_plural': 'منوها'},
        ),
    ]
